import type { NextPage } from "next";
import { useSession, signIn } from "next-auth/react";
import Head from "next/head";
import React, {useEffect} from "react";
import { useRouter } from "next/router";

const login: NextPage = () => {

  const {data: session} = useSession();
  const router = useRouter();

  useEffect(() => {
    if(session?.user) {
      router.push("/")
    }
  },[session])

  return (
    <div>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {session ? (
        <main className="w-screen h-screen bg-blue-gray-800 text-cool-gray-100 flex  justify-center items-center">
          <h1 className="font-bold sm:text-3xl mb-20">Redirecting...</h1>
        </main>
      ) : (
        <main className="w-screen h-screen bg-blue-gray-800 text-cool-gray-100 flex flex-col justify-evenly items-center">
          <h1 className="font-bold sm:text-3xl mb-20">Notes</h1>
          <button
            onClick={() => signIn()}
            className="px-3 py-1 bg-sky-400 ring hover:scale-150"
          >
            Login / Signup
          </button>
        </main>
      )}
    </div>
  );
};

export default login;
